import { StyleSheet } from 'react-native';

export const theme = {
  background: '#000000',
  surface: '#1a1a1a',
  inputBg: '#2a2a2a',
  border: '#e8e8e8',
  text: '#f0f0f0',
  textMuted: '#b0b0b0',
  error: '#ff6b6b',
  placeholder: '#888888',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
  },
  content: {
    padding: 20,
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    color: theme.text,
  },
  subtitle: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    color: theme.textMuted,
  },
  section: {
    marginVertical: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
    color: theme.text,
  },
  label: {
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 5,
    marginTop: 10,
    color: theme.textMuted,
  },
  itemContainer: {
    padding: 15,
    backgroundColor: theme.surface,
    borderRadius: 8,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: theme.border,
  },
  itemTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
    color: theme.text,
  },
  statusContainer: {
    padding: 15,
    backgroundColor: theme.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.border,
  },
  statusLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
    color: theme.text,
  },
  status: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.text,
  },
  networkLabel: {
    fontSize: 14,
    color: theme.textMuted,
    marginTop: 5,
  },
  loadingContainer: {
    alignItems: 'center',
    marginVertical: 20,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: theme.textMuted,
  },
  buttonContainer: {
    marginVertical: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: theme.inputBg,
    color: theme.text,
    marginBottom: 10,
  },
  inputError: {
    borderWidth: 1,
    borderColor: theme.error,
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#3a2020',
    color: theme.text,
    marginBottom: 10,
  },
  fieldError: {
    color: theme.error,
    fontSize: 12,
    marginTop: -8,
    marginBottom: 10,
    marginLeft: 4,
  },
  multilineInput: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  detailCard: {
    backgroundColor: theme.surface,
    borderRadius: 8,
    padding: 15,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: theme.border,
  },
  detailCardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    color: theme.text,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    paddingBottom: 10,
  },
  emptyText: {
    fontSize: 14,
    color: theme.textMuted,
    textAlign: 'center',
    fontStyle: 'italic',
    marginVertical: 20,
  },
  deliveryItem: {
    backgroundColor: theme.surface,
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderLeftColor: theme.border,
  },
  deliveryTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 5,
    color: theme.text,
  },
  deliveryDetail: {
    fontSize: 14,
    color: theme.textMuted,
    marginBottom: 2,
  },
  infoText: {
    fontSize: 14,
    color: theme.textMuted,
    textAlign: 'center',
    fontStyle: 'italic',
    marginVertical: 10,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 100,
  },
  switchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    marginBottom: 10,
  },
  switchLabel: {
    fontSize: 16,
    color: theme.text,
    flex: 1,
  },
  keyboardPadding: {
    height: 200,
  },
  healthBanner: {
    padding: 12,
    borderRadius: 8,
    marginHorizontal: 16,
    marginVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  healthChecking: {
    backgroundColor: theme.surface,
    borderColor: theme.border,
    borderWidth: 1,
  },
  healthSuccess: {
    backgroundColor: '#1a2e1a',
    borderColor: '#4ade80',
    borderWidth: 1,
  },
  healthError: {
    backgroundColor: '#2e1a1a',
    borderColor: theme.error,
    borderWidth: 2,
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  healthText: {
    fontSize: 14,
    color: theme.text,
    marginLeft: 8,
    fontWeight: '500',
  },
  healthErrorText: {
    fontSize: 16,
    color: theme.error,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 4,
  },
  healthErrorSubtext: {
    fontSize: 12,
    color: theme.textMuted,
    textAlign: 'center',
    marginBottom: 8,
    fontFamily: 'monospace',
  },
  debugInfo: {
    backgroundColor: theme.surface,
    padding: 8,
    borderRadius: 4,
    marginTop: 8,
    borderWidth: 1,
    borderColor: theme.border,
  },
  debugText: {
    fontSize: 10,
    color: theme.textMuted,
    fontFamily: 'monospace',
  },
});

export type AppTheme = typeof theme;
export type AppStyles = typeof styles;
